### PR TITLE
INBOX: Ability to DELETE an item from INBOX #369

### PR DESCRIPTION
**Pull request by ArindamReact**
In this pull request, I've updated the 
1. item.ts in which I've returned the functionality of removing the item from inbox
2. added backspace/delete icon in inbox.ts
3. also added main delete function in home.vue

### CODE REVIEW

**Review by chrisns — DISMISSED** [review]
Please add a test

**Comment by ArindamReact** [comment]
ok, will add test and push again for review.

**Comment by ArindamReact** [comment]
ok, will add test and push again for review.

**Review by mrjamieeast — APPROVED** [review]

**Comment by mrjamieeast** [comment]
@ArindamReact Hi - this has been merged but is not showing up on live site?

**Pull request merged**
