### PR TITLE
Run time clip length

### PR DESCRIPTION
**Pull request by ArindamReact**
In this PR we've added All time of the clip fields in the top of the script section. we've made the changes in following files
1. Home.vue
2. Script.vue

### CODE REVIEW

**Comment by mrjamieeast** [comment]
this doesn't work for me - nothing happens

**Comment by mrjamieeast** [comment]
Screenshot 2022-07-22 at 14 04 16

**Comment by chrisns** [comment]
needs a test case

**Review by mrjamieeast — APPROVED** [review]

**Comment by mrjamieeast** [comment]
Please use font face and size as per design

**Comment by mrjamieeast** [comment]
@ArindamReact please address test failure

**Comment by ArindamReact** [comment]
> Please use font face and size as per design

Can you please let us know which font family and font size we need to apply

**Comment by mrjamieeast** [comment]
> 

Bree Serif Regular - 24px

**Review by mrjamieeast — APPROVED** [review]

**Pull request merged**
