### PR TITLE
SCRIPT2 : Create input fields: #241

### PR DESCRIPTION
**Pull request by ArindamReact**
In this pull request
1. I've added three new fields in the UI, in script section
2. save data in the firestore

### CODE REVIEW

**Review by mrjamieeast — APPROVED** [review]

**Comment by ArindamReact** [comment]
Hello @mrjamieeast 
I've resolved the comments, and pushed on this. Please approve it and merge it to main.

Thank you

**Comment by ArindamReact** [comment]
Also please test on branch URL, because it is updated now. Preview URL is not updated

**Review by mrjamieeast — COMMENTED** [review]
There are a hell of a lot of warnings here - Is there any reason in particular they are being ignored?

**Comment by chrisns** [comment]
needs some tests

**Comment by ArindamReact** [comment]
@chrisns please test now

**Comment by chrisns** [comment]
No, I mean write some cypress tests to prove it works :)

**Review by mrjamieeast — APPROVED** [review]

**Pull request merged**
