### PR TITLE
SCRIPT 4a: Ability to DELETE a CLIP field #372

### PR DESCRIPTION
**Pull request by ArindamReact**
In this request, I've made the changes in 2 files
1. scripts.vue in which I added delete function defination and 
2. clipfield.vue in which I've added delete button and pass data through props and emit delete function also.

### CODE REVIEW

**Review by mrjamieeast — APPROVED** [review]

**Comment by mrjamieeast** [comment]
@ArindamReact please fix test failures

**Comment by mrjamieeast** [comment]
@ArindamReact this deletes the wrong clip field. Rather than deleting the field you are selecting, it always deleted the bottom one. It needs to delete the field you are clicking on.

**Comment by chrisns** [comment]
Any chance of more meaningful commit messages than 'stable'? Especially when it is in fact, very much not.
You do have the ability to run all the lint and cypress tests locally. I'm not sure why there's so many CI fails

**Comment by ArindamReact** [comment]
Ok @chrisns I will make sure about meanigfull commit commet from next time

**Comment by chrisns** [comment]
Please don't make line changes just to run the ci
You can rerun ci jobs
You can make empty commits
You can run all the tests locally
If the builds are non-deterministic I.e. rerunning them yields different results, that's a problem that needs to be fixed immediately

**Comment by mrjamieeast** [comment]
@ArindamReact please make Key0, Key1 etc invisible

**Review by mrjamieeast — APPROVED** [review]

**Pull request merged**
