### PR TITLE
Script2

### LINKED ISSUE #241: SCRIPT2 : Create input fields:
Title
Special Day
Birthdays

See screenshot

### PR DESCRIPTION
**Pull request by bhavinsen**
Fixed #241

### CODE REVIEW

**Comment by chrisns** [comment]
what is this? appears to include work also in #307 ?

**Comment by mrjamieeast** [comment]
@bhavinsen please style as per screengrab

**Comment by chrisns** [comment]
> > what is this? appears to include work also in #307 ?
> 
> Nope - it's the title/birthday fields at the top - 307 was just the 7 content areas

no, i mean the code includes stuff that was in #307, which is probably why it now has conflicts

**Comment by mrjamieeast** [comment]
@bhavinsen please review - also please only include code relevant to the ticket.

**Review by ArindamReact — APPROVED** [review]

**Comment by ArindamReact** [comment]
approved

**Review by ArindamReact — DISMISSED** [review]

**Review by ArindamReact — DISMISSED** [review]

**Comment by ArindamReact** [comment]
I have found 7 undefined value calls.
he has taken string docname = 'todaysdate' and called it as the object that is why it is giving error on 7 places, by using of docname he is calling 'docname.value' which is undefined because we have initialized docname as the string.

image
image

**Comment by mrjamieeast** [comment]
Ok great - can you fix?

**Review by ArindamReact — APPROVED** [review]

**Review by ArindamReact — DISMISSED** [review]

**Pull request closed without merging**
