### PR TITLE
Drag item from Draft to script

### PR DESCRIPTION
**Pull request by ArindamReact**
1. I've added functioanlity of drag from draft to script
2. It will drop to the same slot no. from which it dragged
3. Previously data is not saving in script, now it is working fine

### CODE REVIEW

**Comment by mrjamieeast** [comment]
Hello - This doesn't work for me

**Comment by ArindamReact** [comment]
We are still working to complete drag and drop feature. We were just pushed code to share progress. Will update PR summary as soon as it will be fully functional.

**Comment by mrjamieeast** [comment]
Ok thanks

**Comment by mrjamieeast** [comment]
@ArindamReact This still does not work for me

**Comment by mrjamieeast** [comment]
It does not stay in the script for me.

https://user-images.githubusercontent.com/104105362/179709888-a6c557d7-1980-4c09-951b-bb7171807a1c.mov

**Review by mrjamieeast — APPROVED** [review]

**Pull request merged**
