### PR TITLE
SCRIPT: Create ability to export script into google doc format, into google drive folder #251

### PR DESCRIPTION
**Pull request by ArindamReact**
similar to copy slot in the draft, but instead copy the html for the whole script to clipboard so that it can be pasted into google docs/word/whatever else -- done

### CODE REVIEW

**Comment by ArindamReact** [comment]
@mrjamieeast can you please check on preview and confirm me that this is correct what we've done.

**Comment by mrjamieeast** [comment]
It doesn't copy anything to clipboard for me.

**Comment by ArindamReact** [comment]
[screencast-nimbus-capture-2022.08.08-23_10_48.webm](https://user-images.githubusercontent.com/105204781/183480087-5881628d-8f3c-4060-b7b7-a798a9709fa8.webm)

**Comment by ArindamReact** [comment]
@mrjamieeast please check the video, and let me know your opinion

**Comment by mrjamieeast** [comment]
I have no idea what I'm looking at. This is not what the ticket was requesting.
"Create ability to export script into google doc format"

Where is that?

**Comment by mrjamieeast** [comment]
I do not know why the original request was changed. THIS is what I need:

"Once a script has been finalised - a user should be able to Export/Send the script as a Google Doc to a Google Drive destination for the narrator to see.

Ideally the text that gets exported will ONLY be the Script."

This functionality is so editors can email scripts to hosts for their read.
It should ideally just contain the following:

1. TITLE
2. special days
3. birthdays
4. script text
5. <br> or something simliar for clip - eg:

**_

> Hello and welcome to the smart 7!
> 
> CLIP
> 
> Coming up on today's episode
> 
> CLIP

_**

**Review by chrisns — DISMISSED** [review]
Please make sure there's some tests

**Comment by ArindamReact** [comment]
I've made the pdf download and open in new tab, but uploading we're not getting able to succeed. Kindly please check the same and let me know if you have any opinions on it.

**Comment by mrjamieeast** [comment]
I can live without google sync 

Jamie East
07515340555
@jamieeast

**Comment by mrjamieeast** [comment]
One question - Can we add styling to PDF or no?
Only font weight/underline etc

Also - title says DRAFT DORIS rather than DAFT DORIS

**Comment by ArindamReact** [comment]
@mrjamieeast Yes it is possible to add style to it let us know what style should be added

**Comment by mrjamieeast** [comment]
> https://beef9616.newsdesk.pages.dev

Something like this?

https://docs.google.com/document/d/1tP4sbRRKNB-Tel0jtrSzVgS5k2D6ot3LyvjKbvSLick/edit?usp=sharing

**Review by mrjamieeast — APPROVED** [review]

**Pull request merged**
