### PR TITLE
Drag items from inbox into draft and remove form index v2

### PR DESCRIPTION
**Pull request by Kareem-Shanti**

### CODE REVIEW

**Review by chrisns — CHANGES_REQUESTED** [review]
what is going on here, I thought we were abandoning all this work and restarting from scratch, close the pr and delete the branch?

**Comment by Kareem-Shanti** [comment]
> what is going on here, I thought we were abandoning all this work and restarting from scratch, close the pr and delete the branch?

we resolved #272 and #357 as a new pr .. kindly merge this in the live env

**Comment by chrisns** [comment]
> > what is going on here, I thought we were abandoning all this work and restarting from scratch, close the pr and delete the branch?
> 
> we resolved #272 and #357 as a new pr .. kindly merge this in the live env

you've got merge conflicts, so its not worth me even looking to review it until thats resolved and the tests pass

**Comment by chrisns** [comment]
What the, why are you trashing the package-lock.json

Please don't do that for what should be really super obvious reasons

**Comment by Kareem-Shanti** [comment]
> 

The merging process of the PR was getting a conflict from your end, so for QA purpose we removed the file package-lock.json, which we have a backup also with us , we will be pushing that from our end to the specific PR

**Comment by chrisns** [comment]
Er what? No.
Please can you look into how to use git properly to solve this, I'm not even sure why you're changing the packages at all in the pr to begin with. Proposing a PR that removes it is not the answer

**Comment by Kareem-Shanti** [comment]
> Er what? No. Please can you look into how to use git properly to solve this, I'm not even sure why you're changing the packages at all in the pr to begin with. Proposing a PR that removes it is not the answer

Yes Chrisns, definitely  we will resolve that issue, by mistake it was deleted for testing purpose in future we will be more careful about that, and we have deleted it from our branch, if we done anything wrong please guide us.

**Comment by chrisns** [comment]
there is no 'my end' there is the `main` branch and your feature branch, the conflict is from changes in your feature branch.
I'm afraid I don't have the time to guide you on this much, you'll need to figure it out yourselves or go with the previous advice of abandon this branch and create the work afresh, not just another branch with the same commits.

**Comment by chrisns** [comment]
closing pr, deleting branch, hopefully we can just move on now.

**Pull request closed without merging**
