### PR TITLE
3 bugs fixed -- 393, 379, 382

### PR DESCRIPTION
**Pull request by ArindamReact**
In this PR, we've resolved three bugs 
1. https://github.com/DaftDoris/newsdesk/issues/393
2. https://github.com/DaftDoris/newsdesk/issues/379
3. https://github.com/DaftDoris/newsdesk/issues/382

In first bug, we've changed the method to snapshot instead of setdoc
and in second one, we've added new clickable filed instead of input clickable because it is not possible to input file at a time and make it clickable
and in third one there is a CSS change

### CODE REVIEW

**Review by chrisns — CHANGES_REQUESTED** [review]
some tests for these fixes would be great

**Comment by mrjamieeast** [comment]
Clickable URL doesn't work - looks all wrong. Other two are fine. Will merge once that other one is fixed.
Screenshot 2022-08-02 at 13 59 20

**Comment by mrjamieeast** [comment]
Click works but now bleeds across other cells @ArindamReact 

Screenshot 2022-08-03 at 22 44 50

**Review by chrisns — CHANGES_REQUESTED** [review]
Write tests

**Comment by ArindamReact** [comment]
> Write tests

Please let me know what test case you need for these, because these are cosmetic changes

**Comment by chrisns** [comment]
393. Delete a thing. Assert its not there anymore?

**Comment by chrisns** [comment]
379 assert the thing exists and is clickable. Has what you expect in the dim object

**Comment by chrisns** [comment]
Basically write the tests so regression bugs don't happen. While you might thing it's cosmetic, it's not that simple. And even if it was, it's still something to avoid breaking in the future

**Comment by mrjamieeast** [comment]
This has failed

**Review by chrisns — APPROVED** [review]

**Pull request merged**
