### PR TITLE
Show word count #492

### PR DESCRIPTION
**Pull request by Sourav-React**
I've added the text on UI also added some chamge of to current count logic and it is working fine

### CODE REVIEW

**Review by mrjamieeast — CHANGES_REQUESTED** [review]
Doesn't work
Screenshot 2022-09-04 at 15 10 01

**Comment by ArindamReact** [comment]
> Doesn't work Screenshot 2022-09-04 at 15 10 01

Hello @mrjamieeast 

We cannot track the word count entered in the WSYWG Editor, because it return the HTML. We can only track the clipfield word count. Let me know if you've any queries.

**Comment by mrjamieeast** [comment]
@ArindamReact Can you not count the words within a <p> tag? I can't believe something so basic isn't possible? @chrisns ?

**Comment by chrisns** [comment]
does the returned html not have a `.textContent` property on it? if not google says: https://dev.to/sanchithasr/3-ways-to-convert-html-text-to-plain-text-52l8

**Comment by mrjamieeast** [comment]
@ArindamReact what has changed?

**Review by mrjamieeast — APPROVED** [review]

**Pull request merged**
